apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-oqdp
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-oqdp@sha256:2393a183191e5d765e1f52c85eca883d32a56314163b5c2200a8811c43027404
        name: my-nodejs
        resources: {}
status: {}
